name: deploy-rds
on:
  workflow_dispatch:

jobs:
  create-rds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Create RDS MySQL Instance
        run: |
          aws rds create-db-instance \
            --db-instance-identifier g11-db-instance \
            --db-instance-class db.t3.micro \
            --engine mysql \
            --allocated-storage 20 \
            --master-username ${{ secrets.DB_USER }} \
            --master-user-password ${{ secrets.DB_PASS }} \
            --vpc-security-group-ids sg-042896fe2dea4c357 \
            --backup-retention-period 7 \
            --availability-zone eu-west-3a

      - name: Wait for RDS to be available
        run: |
          echo "Waiting for RDS to be ready..."
          aws rds wait db-instance-available --db-instance-identifier g11-db-instance

      - name: Get RDS Endpoint
        run: |
          DB_HOST=$(aws rds describe-db-instances \
            --db-instance-identifier g11-db-instance \
            --query "DBInstances[0].Endpoint.Address" \
            --output text)

          echo "MYSQL_HOST=$DB_HOST" >> .env
          echo "MYSQL_USER=${{ secrets.DB_USER }}" >> .env
          echo "MYSQL_PASSWORD=${{ secrets.DB_PASS }}" >> .env
          echo "MYSQL_DB=${{ secrets.DB_NAME }}" >> .env

          cat .env  # Afficher pour debug

      - name: Commit and Push .env file
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .env
          git commit -m "Add .env file with MySQL credentials"
          git push
