name: deploy-rds
on:
  workflow_dispatch
jobs:
  create-rds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Create RDS MySQL Instance
        run: |
          aws rds create-db-instance \
            --db-instance-identifier g11-db-instance \
            --db-instance-class db.t4g.micro \
            --engine mysql \
            --allocated-storage 20 \
            --master-username ${{ secrets.DB_USER }} \
            --master-user-password ${{ secrets.DB_PASS }} \
            --vpc-security-group-ids sg-042896fe2dea4c357 \
            --backup-retention-period 7 \
            --availability-zone eu-west-3a
