name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ls
      - uses: docker/build-push-action@v6.13.0
        with:
          push: true
          tags: plbls2/getting-started:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_TOKEN }}
      - run: docker images

# Checkout code
# -ls
# build
# images
# push
