name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      - name: Use the version
        run: |
          echo ${{ steps.version.outputs.version }}
      - name: Use the previous version
        run: |
          echo ${{ steps.version.outputs.previous-version }}
      - name: List files
        run: ls
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ steps.version.outputs.version }} .
      - name: List Docker images
        run: docker images
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ steps.version.outputs.version }}
