name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - run: ls
      - uses: docker/build-push-action@v6.13.0
      - run: docker images

# Checkout code
# -ls
# build
# images
# push
