name: build-docker
on: [push]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Increment version
        id: version
        run: |
          VERSION=$(cat .git-version)
          VERSION=$((VERSION + 1))
          echo "version=$VERSION" >> $GITHUB_ENV
          echo $VERSION > .git-version
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ env.version }} .
      - name: List Docker images
        run: docker images
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ env.version }}
