name: build-docker
on:
  workflow_dispatch:
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Increment version
        id: version
        run: |
            VERSION=$(cat git-version)
            IFS='.' read -r -a VERSION_PARTS <<< "$VERSION"
            MAJOR=${VERSION_PARTS[0]}
            MINOR=${VERSION_PARTS[1]}
            PATCH=${VERSION_PARTS[2]}
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "new_version=$NEW_VERSION" >> $GITHUB_ENV
            echo $NEW_VERSION > git-version
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ env.new_version }} .
      - name: List Docker images
        run: docker images
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/getting-started:${{ env.new_version }}
